image: python:3.7.4

pipelines:
  default:
    - step:
        name: Setup
        caches:
          - pip
        script:
          - echo "$(cat common/_version.py) + \".$BITBUCKET_BUILD_NUMBER\"" > common/_version.py
          - pip install -r requirements.txt
          - python setup.py develop
          - python -c "from common import *"
          - python -c "from common import __version__ as v; print('common_classes_mx, version:', v)"
