image: python:latest

pipelines:
  default:
    - step:
        name: Setup, Test, Deploy
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python setup.py develop
          - python -m pytest tests
          - python setup.py bdist_wheel
          - git add dist/*
          - git commit -m "[skip ci] Update wheel"
          - git push
