image: python:3.7.5

pipelines:
  default:
    - step:
        name: Setup
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python setup.py develop
          - python -c "from common import *"
          - python -c "from common import __version__ as v; print('common_classes_mx, version:', v)"
  branches:
    master:
      - step:
          name: Version
          caches:
            - pip
          script:
            - IFS='+'
            - read -ra ARR <<< "$(cat common/_version.py)"
            - echo "${ARR[0]} + \".$BITBUCKET_BUILD_NUMBER\"" > common/_version.py
            - git add common/_version.py
            - git commit -m "[skip CI]"
            - git push
            - pip install -r requirements.txt
            - python setup.py develop
            - python -c "from common import *"
            - python -c "from common import __version__ as v; print('common_classes_mx, version:', v)"
