image: python:latest

pipelines:
  default:
    - step:
        name: Setup
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python setup.py develop
          - python -m pytest
