image: python:latest

pipelines:
  pull-requests:
    dev:
      - step:
          name: Setup, Test, Deploy
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python setup.py develop
            - python -m pytest tests
            - python setup.py bdist_wheel
            - git add dist/*
            - git commit -m "[skip ci] Update wheel"
            - git push
  branches:
    '**':
      - step:
          name: Setup, Test
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python setup.py develop
            - python -m pytest tests
